### ISSUE TITLE
Missing dependencies on bdep ci

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/imgui#10]
Some system dependencies on the CI are missing to allow a successful build.
Basically the `Vulkan`, `OpenGL` and `X11` dependencies are missing on some machines.

See also this build: https://ci.stage.build2.org/@4d3020fd-c6c0-40b2-8be6-c57213b24c77

AFAIK Debian based systems need to install the following packages

* libvulkan-dev
* xorg-dev
* libx11-dev
* libxrandr-dev
* libglu1-mesa-dev
* freeglut3-dev 
* mesa-common-dev

@boris-kolpackov Is there anything I can do about this? E.g. install dependencies ad-hoc just like in the GitHub CI?

For Vulkan on MacOS, Windows and Linux @Klaim suggested: 

> LunarG's Vulkan SDK should be everything needed to be able to build with it on MacOS, Windows and Linux (and some other platforms apparently. Your libvulkan-meta package already does the rest of the wiring.
> I did try the libvulkan-meta package in the past on Windows (11) and it was working as expected.
> 
> It's probably not installed on build2's CI at the moment (which is what I expected). Unfortunately it means that publishing this package on cppget implies not testing it on that CI. (it's also one of the reasons I asked for the null backend example to be run as a test, that's the only thing we can build and run on build2's CI right now).

For Vulkan on MacOS and Windows @Swat-SomeBug  suggested:

> At the moment I have the Vulkan SDK on my local windows machine. I’m not sure if there is a package for it.
> I believe there’s Vulkan SDK for MacOs as well. Not sure if homebrew has it.
> But I suspect there maybe some manual install steps on Windows and MacOs for Vulkan.

**Comment by boris-kolpackov** [comment]
> AFAIK Debian based systems need to install the following packages

I've installed these on the `linux_debian_11-gcc_12.1` VM -- could you test it and confirm nothing else is missing before I replicate it to the rest of the machines?

You can submit the CI job just for this configuration by passing `--build-config linux_debian_11-gcc_12.1` to `bdep-ci`.


> For Vulkan on MacOS, Windows and Linux @Klaim suggested:
> For Vulkan on MacOS and Windows @Swat-SomeBug suggested:

I am reluctant to install anything that comes from third parties on CI VMs. Does GitHub CI comes with this stuff pre-installed or do you just install it yourself as part of the build?

Also, what is the relationship between these Vulkan SDKs and the [`Vulkan-Headers`/`Vulkan-Hpp`]( `Vulkan-Headers`/`Vulkan-Hpp) packages by @Wmbat ?

**Comment by Klaim** [comment]
> Also, what is the relationship between these Vulkan SDKs and the Vulkan-Headers/Vulkan-Hpp packages by @Wmbat ?

Vulkan Headers (from Kronos Group - which standardizes OpenGL and Vulkan among other things) is the official interface published for C (and C++ via Vulkan-HPP): https://github.com/KhronosGroup/Vulkan-Headers

Vulkan SDK (from LunarG) is a recommended cross-platform (desktop) implementation for development. There are others but they usually are for specific hardware (like game consoles).

Vulkan is technically an interface to talk to the graphic driver, so it's the GPU drivers or the OS that will provide the actual implementation binaries, in particular for the users, but while developing you need both and the implementation needs to provide some debug info (and other higher level tooling for debug better than poking at the driver and crashing the system).
That's why there is an SDK. You can actually compile Vulkan-dependent code using only Vulkan-Header  (assuming you don't use the higher layer stuffs, which is optional) but you might not be able to link (if you don't have the .lib necessary on windows for example) or run (if the dlls are not installed on windows for example, or if you didn't build in release mode). 

> Does GitHub CI comes with this stuff pre-installed or do you just install it yourself as part of the build?

For Ubuntu we install a few packages: https://github.com/build2-packaging/imgui/blob/main/.github/workflows/build2.yml#L43

For Windows and MacOS another github-action is being used to make the Vulkan SDK available: https://github.com/build2-packaging/imgui/blob/main/.github/workflows/build2.yml#L68

**Comment by Klaim** [comment]
Looking at how the github action installs the SDK, it seems it ~~mainly~~ also install all the libs provided by Khronos Group, which is a lot but there is Vulkan-Header in there. See: https://github.com/humbletim/setup-vulkan-sdk

~~This suggests that packaging most or all of these might be a viable solution to make it work on the CI (if there is a software implementation at least, not using the gpu?).~~
Nevermind, that github-actions still relies on the LunarG implementation.

**Comment by Klaim** [comment]
> I am reluctant to install anything that comes from third parties on CI VMs.

I have been thinking about this for some time (because I'm a gamedev and a lot of what I need requires this kind of setup).

I was thinking that maybe a kind of submission system allowing requesting to check the package owner's CI instead of relying completely on the community CI would help? Something like: I've made a lib requiring something like `fmod` (the audio library), can't run it on the `build2` CI so when I send my package for publishing I deactivate almost all CI checks but I set a flag or command that requests a package reviewer to come check my own public CI (probably set with github-actions), see if it's good enough. I'm not sure if that would be sufficient for publishing with reasonable security? Also that might be a parallel discussion.

Alternatively we can also let these packages be used only through github repositories, but there is obvious drawbacks to that.

**Comment by Rookfighter** [comment]
> Also, what is the relationship between these Vulkan SDKs and the [Vulkan-Headers/Vulkan-Hpp](https://github.com/build2-packaging/imgui/issues/%60Vulkan-Headers%60/%60Vulkan-Hpp) packages by @Wmbat ?

I am not too experienced with Vulkan overall, but my understanding was that the Vulkan-Headers repository is supposed to just describe the Vulkan API (just as Klaim explained).
You can also use these headers to complement Vulkan Binaries on your system when you do not have a dev SDK of Vulkan installed. Typically, you do not need to do that when you have installed a proper Vulkan SDK on your system, which just ships the headers like `libvulkan-dev`. Also you would have to match the version of your installed Vulkan binaries with the correct version of Vulkan-Headers. IMO, using a non-SDK Vulkan installation and a matching Vulkan-Headers package should be disregarded as development environment.

**Comment by Rookfighter** [comment]
Here's the `bdep ci` build. https://ci.stage.build2.org/@adb339b7-66e5-408d-9299-d423f22d921c

Looks good to me, however do you know why it tries to build the Direct X packages on Debian? To my understanding the `builds` parts of the manifest should avoid the build on non-windows systems.

**Comment by boris-kolpackov** [comment]
> however do you know why it tries to build the Direct X packages on Debian?

That's because you have overridden the `builds` value in the manifest when you specified the `--build-config` `bdep-ci` option (the man page has the details on the override semantics).

**Comment by boris-kolpackov** [comment]
Ok all the Linux VMs in the `default` build class have these additional packages installed.

**Comment by Rookfighter** [comment]
Closed as Linux VMs work and nothing else is currently planned.
